// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR_jdE8p3KlhR4OtN5BcjWDqtjlHs_M2M',
    appId: '1:103496524084:web:c09c5b032221bb6a924561',
    messagingSenderId: '103496524084',
    projectId: 'gooddeed-37023',
    authDomain: 'gooddeed-37023.firebaseapp.com',
    storageBucket: 'gooddeed-37023.firebasestorage.app',
    measurementId: 'G-L5PEM99HXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt1n5y_8moLHXVsWutEjT7-KEGfAkPf0A',
    appId: '1:103496524084:android:ab6ad4ec4b32f7b0924561',
    messagingSenderId: '103496524084',
    projectId: 'gooddeed-37023',
    storageBucket: 'gooddeed-37023.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVkR7h1e2xE3Cczd6d6ldSSfncwFlE7PM',
    appId: '1:103496524084:ios:545cdf81803eafe6924561',
    messagingSenderId: '103496524084',
    projectId: 'gooddeed-37023',
    storageBucket: 'gooddeed-37023.firebasestorage.app',
    iosClientId: '103496524084-ak40iu45c3bjm3omma00koo9op2flgcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.good',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVkR7h1e2xE3Cczd6d6ldSSfncwFlE7PM',
    appId: '1:103496524084:ios:545cdf81803eafe6924561',
    messagingSenderId: '103496524084',
    projectId: 'gooddeed-37023',
    storageBucket: 'gooddeed-37023.firebasestorage.app',
    iosClientId: '103496524084-ak40iu45c3bjm3omma00koo9op2flgcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.good',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR_jdE8p3KlhR4OtN5BcjWDqtjlHs_M2M',
    appId: '1:103496524084:web:2b6b2210c8092bff924561',
    messagingSenderId: '103496524084',
    projectId: 'gooddeed-37023',
    authDomain: 'gooddeed-37023.firebaseapp.com',
    storageBucket: 'gooddeed-37023.firebasestorage.app',
    measurementId: 'G-R563T28TCP',
  );
}
